jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

spring.application.name: secret-santa
server:
  error:
    include-stacktrace: never

spring:
  sql:
    init:
      mode: always # Permitindo a utilização de um arquivo DATA.SQL para inicializar os dados na nossa base

  mail:
    host: smtp.gmail.com
    port: 587
    username: # seu email
    password: # sua senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/secret-santa?&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true # Atrasa a inicialização do datasource para permitir que os inserts sejam feitos depois que as tabelas estejam criadas

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MYSQL8Dialect
    show-sql: true
profiles:
  active: dev

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}


